CREATE TABLE user(
    username nvarchar(50) NOT NULL,
    password nvarchar(50) NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE connection(
	id_connection int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name nvarchar(50) NOT NULL,
	description nvarchar(300),
	data nvarchar(500),
	PRIMARY KEY (id_connection)
);

CREATE TABLE project(
	id_project int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name nvarchar(50) NOT NULL,
	description nvarchar(300),
	cron_job nvarchar(50),
	PRIMARY KEY (id_project)
);

CREATE TABLE history(
	id_history int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	data blob,
	PRIMARY KEY (id_history)
);

CREATE TABLE query(
	id_query int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	id_connection int NOT NULL,
	name nvarchar(50) NOT NULL,
	description nvarchar(300),
	data nvarchar(500),
	anchor_cell nvarchar(50),
	PRIMARY KEY (id_query),
	FOREIGN KEY (id_connection) REFERENCES connection(id_connection)
);









CREATE TABLE user_connection(
	id_user int NOT NULL,
	id_connection int NOT NULL,
	permissions nvarchar(50),
	FOREIGN KEY (id_user) REFERENCES user(username),
	FOREIGN KEY (id_connection) REFERENCES connection(id_connection),
);

CREATE TABLE user_project(
	id_user int NOT NULL,
	id_project int NOT NULL,
	permissions nvarchar(50),
	FOREIGN KEY (id_user) REFERENCES user(username),
	FOREIGN KEY (id_project) REFERENCES id_project(id_project)
);

CREATE TABLE project_history(
	id_project int NOT NULL,
	id_history int NOT NULL,
	date_update timestamp default current_timestamp,
	FOREIGN KEY (id_project) REFERENCES project(id_project),
	FOREIGN KEY (id_history) REFERENCES history(id_history)
);

CREATE TABLE project_query(
	id_project int NOT NULL,
	id_query int NOT NULL,
	FOREIGN KEY (id_project) REFERENCES project(id_project),
	FOREIGN KEY (id_query) REFERENCES query(id_query)
);








SELECT columns
FROM table
WHERE conditions
ORDER BY columns
LIMIT n